# Generated by Django 5.0.1 on 2024-01-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_training', '0003_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Перевод', 'Перевод')], default='Cash', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
