# Generated by Django 5.0.1 on 2024-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_training', '0006_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8, verbose_name='Цена курса'),
        ),
    ]
