# Generated by Django 5.0.1 on 2024-02-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_training', '0008_payments_is_paid_payments_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_payment',
            field=models.DateField(auto_now_add=True, verbose_name='Дата оплаты'),
        ),
    ]
