# Generated by Django 5.0.1 on 2024-02-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_training', '0009_alter_payments_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
