# Generated by Django 5.0.1 on 2024-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_training', '0010_alter_payments_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Цена курса'),
        ),
    ]
